assembly.py
The assembly process was putting bootstrap chunks into the sandbox
when said chunks were not build dependencies.  In addition it was
failing to run ldconfig in non-bootstrap cases.
This commit fixes that.
=> Adjust assembly process to allow build-essential to complete.

assembly.py, sandbox.py
This is a poor-man's implementation of a need to keep only the
build steps parallel.  It's opposite to how morph deals with it
but perhaps is easier to understand.
=> Ensure we only set MAKEFLAGS during build steps

assembly.py, readme.md, sandbox.py, utils.py
This is a set of fixes and improvements to deployment, which allows systems to be deployed when extensions are in subdirectories as is the case in current master of definitions. It also removes the dependency on morphlib now that all the extensions are in definitions.
NOTE: Some of the deployment extensions still depend on morphlib, so only a subset of the deployment extensions will work on a system without morph.
=> Deployment improvements and fixes

sandbox.py
This should work towards solving #31 and improving reproducibility; as far as I am aware there is no current time standard in YBD, meaning that build reproducibility could be affected by builds being ran in different timezones.
=> ybd: Add environment variable to set timezone to UTC

sandbox.py
This was broken in commit 66cf5ba0b20ec4f6e3c1d99e1b420b455203cef7, sorry.
This fixes issue #45, I've built a build-system-armv7lhf-jetson using this branch.
=> Fix system builds

app.py
Seems the prototype of the exit() function changed.
Traceback (most recent call last):
File "../ybd/ybd.py", line 40, in <module>
with app.setup(target, arch):
File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
return self.gen.next()
File "/home/shared/baserock-chroot-src/ybd/app.py", line 78, in setup
exit(target, 'ERROR: %s is not a git repo' % os.getcwd())
TypeError: exit() takes exactly 3 arguments (2 given)
=> Fix crash on 'xx is not a git repo' error

repos.py
This makes the error message more useful when trying to debug problems.
Example of the new output:
2015-06-08 16:07:04 [stage1-binutils] ERROR: could not find tree for ref
('b1d3b01332ae49a60ff5d6bf53d3a5b1805769c8',
'/home/sam/ybd-builds/cache/gits/git___git_baserock_org_delta_binutils_redhat')
=> Show name of Git repo when resolving a tree fails

repos.py
This is just a matter of handling the bits of the stdlib that have
different names in Python 3.
Building with Python 3 still doesn't work because of some code that tries
to do 'dict1.items() + dict2.items()'. I think that's the only remaining blocker.
=> Fix repos.py to work under Python 3

app.py, assembly.py, definitions.py, sandbox.py
It's less messy to use a separate dict for the clean environment. This
also fixes YBD under Python 3, as you can't do 'dict.items() +
dict.items()' in Python 3.
=> Don't mutate os.environ for each build

assembly.py, ybd.py
The first commit reworks the deploy() function to be less recursive and easier to reason about, as well as putting the recursive call in the correct place to deploy subsystems properly.
The second commit changes the variable names in assemble(), as well as looking in the correct place for the "subsystems" key and not attempting to build clusters.
The third commit adds a shebang to ybd.py so that it can be run directly (i.e. `../../ybd.py clusters/release.morph`), and is pretty unrelated to the others.
=> Support for subsystems in clusters

app.py, sandbox.py, utils.py
Currently the deployment extensions still depend on morphlib and cliapp, but I plan to remove those dependencies by making them instead depend only on code in `extensions/` in the defintions repository. This means that that directory will need to be in PYTHONPATH when the extensions are run.
I've tested using this to deploy a build-system-x86_64 tarball using my WIP branch of definitions that has no external dependencies.
=> Support for running extensions which depend on code in definitions

app.py, sandbox.py
This means that YBD now requires the 0.3.0 release of 'sandboxlib'.
I've tested on Mac OS X (using 'chroot' backend) and Baserock (using 'linux-user-chroot').
=> Support 'chroot' sandboxing as well as 'linux-user-chroot'

sandbox.py, ybd.py
This means that we won't change behaviour half way through a build based
on whether the user suddenly installs linux-user-chroot or something.
And more importantly it stops printing repeated messages on the console.
=> Pick sandboxlib backend once, on startup

readme.md
One letter missing in the 'quick start' instructions, stops it working correctly
=> Correct typo in readme.md

assembly.py, cache.py, definitions.py, sandbox.py, ybd.py
These patches make the Definitions class re-entrant, by storing the state as instance variables rather than class variables, and passing a single instance when it is needed, rather than instantiating a new object each time. This solves the first part of #35.
These patches do **not** solve the second part of #35, that is replacing the dicts with objects.
=> Make Definitions class reentrant

definitions.py
The first and last of these commits are aesthetic-only patches which attempt to make definitions.py slightly clearer. Whether they succeed or not may be a matter of opinion.
The second commit fixes a bug where we were only looking at one level of subsystems, when in fact they can be nested to an arbitrary depth.
=> definitions.py fixes and tidyups

assembly.py
Fixes an issue where deploy_defaults weren't being passed to the configuration extension
=> Pass deploy defaults to extensions

definitions.py
This reverts commit bf6e47a641248f713a64d918c92fb2b17dadbdd3.
It was a poorly thought-out change, and broke things because only
half the validation was split out. It's probably fine to just
leave it where it is for now.
=> Revert "Move the schema validation into a function"

assembly.py, cache.py
Subsystems in clusters can be nested to arbitrary depth, so we need to look deeper than just the first 'subsystems' key.
=> Always inspect subsystems recursively

assembly.py
We need to create a "deplyoment.meta" file for system-version-manager, else any of the default deploy options won't get passed
=> system-version-manager needs a deployment manifest for upgrades

app.py
If a git repo has no tags, a bare "git describe" will return an error.
=> Identify git repo even if it has no tags

assembly.py
It's quite easy to forget that "true" and "false" are special words in YAML,
and write "false" to halt the build process while debugging. This was treated
as a Boolean instead of a string, so causes an unhelpful error in ybd.
Since there is no use for booleans in morphologies, they should be treated as
strings.
=> Treat True and False as actual commands, rather than booleans.

cache.py
The 'data' parameter is not optional. Also, it's handy to show
the file it's looking for.
=> Fix broken call to app.exit()

scripts/build-and-check-reproducibility.sh
This sets off two consecutive builds of a system passed to the script as an
argument, obtaining the sha1sum of all files in the build upon completion,
then obtaining a file showing which SHA1 values differ between the two
builds.
=> Add script to check reproducibility of a system

sandbox.py
MIPS64 needs a different abi of "abi64".  Also there was a mistake in the "cpu" names for little-endian MIPS systems.
=> Fix for MIPS64 and MIPS little-endian

app.py
Warnings reported with warnings.warn() will now only appear to the user
the first time they are reported. Previously the same message could be
repeated each time warnings.warn() was called.
=> Don't print duplicated warning messages

app.py
Commit f8befae1139490e39a1f18d0a554fa9b7321dc13 added a warning filter
before all the other filters. This causes some uninteresting warnings
generated by Python due to bad code in installed libraries to start
appearing, in some cases. If add the warning filter *after* the existing
filters then these warnings remain hidden.
=> Fix warnings filter

assembly.py, buildsystem.py
This is a feature introduced as part of the Baserock definitions format
version 6.
I've tested this against current Baserock reference system definitions (format version 5) and my example version 6 definitions.
=> Allow specifying 'build-system' for a chunk in the containing stratum

config/defaults.conf
... instead the more common autogen[.sh]
=> config/defaults.conf: Some autotools projects use bootstrap[.sh]

ybd/cache.py
Its sometimes useful to know what artifacts a system you built is composed of.
This patch will allow the user to output this information, in json,
to a file. This can be done by adding  the `cache-log:` parameter, followed
by a suitable file name, to your ybd.conf.
=> Facilitate artifact log file generation for systems

ybd/sandbox.py
It's possible there are versions of mount that infer what
you want from '-t type', or perhaps other magic is involved.
Fixes the mount/umount errors seen when building on concourse (not tested with baserock, but I don't see why it should break there)
=> mount expects the thing you are mounting to be specified

readme.md, ybd/app.py, ybd/assembly.py
This is version 2 of my previous pull request. It corrects the following issues:
* riemann-server and riemann-port are no longer in ybd.conf by default
* If riemann-server is not defined, then no riemann events will be fired
* If a server is defined but cannot be contacted (eg it is down), ybd will timeout after 30 seconds
* Fully pep8 compliant
=> [V2] Riemann events

ybd/repos.py
Repositories are initialised and updated in gits without touching config, if a repo requires updating (due to a missing ref) and is found to be non-bare, reinitialise it as a bare repo and fetch.
I considered not nuking the contents of the gitdir and just setting the relevant config, but it seems cleaner (and perhaps more robust) to do it this way.
=> Don't unnecessarily touch git config to fetch from gits

kbas/__main__.py, ybd/cache.py, ybd/repos.py
This branch simply changes all the call to os.rename() for shutil.move(), which will use os.rename() internally in the case that the destination happens to be on the same file system.
Not all changes in the branch are required, however it's better when reading the code if all moves are made with one API, this way we reduce the risk of os.rename() creeping back in places where it can be incorrect.
=> Use move semantics instead of renames across the board

ybd/definitions.py
This patch does not cause the build to bail out, which it probably
should, but at least meaningful parse errors are printed to the
console instead of just: "WARNING: problem loading <file>"
Instead an actual parse error sample looks like:
WARNING: Error parsing <file> while scanning for the next token
found character '\t' that cannot start any token
in "<string>", line 20, column 1:
GNU_TRIPLE=${GNU_TRIPLE}eabi
^
=> definitions.py: Log YAML parse errors while loading definitions

readme.md, ybd/cache.py, ybd/config/ybd.conf
This changes the default behaviour of ybd so that it does not silently delete
artifacts when disk space is low
=> Change default min-gigabytes config to 0

ybd/deployment.py
This fixes https://github.com/devcurmudgeon/ybd/issues/213
When a subsystem is deployed, ybd rewrites the 'location' parameter of the
subsystem in the cluster definition such that it is prefixed with the path of
the temporary deployment directory for the containing system, so that it is
deployed into the containing system's unpacked tree.
Instead, ybd it prefixed the strings 'location' and 'upgrade-location' with
this path, producing an incorrect path for the subsystem deployment. As a
result, subsystems which are referred back to, in this case the initramfs
subsystem, are not found, in this case producing the following error:
Failure to deploy system to genivi-demo-platform-x86_64-generic.img
ERROR: INITRAMFS_PATH specified, but file does not exist
16-04-29 00:02:17 [0/14/129] …
=> Fix subsystem deployment
